### ISSUE TITLE
i get this error

### ISSUE THREAD

**Issue by Hamidriyahi** [Q1001001/HamsterKombatBot#1]
root@ht:~/HamsterKombatBot# python3
conf.json         def_conf.json     .git/             hamster.py        README.md         requirements.txt
root@hid-soft:~/HamsterKombatBot# python3 hamster.py
  File "/root/HamsterKombatBot/hamster.py", line 784
    logger.info(f"Continue in {remainsDelay} sec ({datetime.fromtimestamp(
                ^
SyntaxError: unterminated string literal (detected at line 784)

**Comment by Q1001001** [comment]
fixed. Please, update `hamster.py`
It was a bad idea to use `"` inside the f-string.
