### ISSUE TITLE
SyntaxError: f-string: unmatched '('

### ISSUE THREAD

**Issue by fastnfuriousbd** [Q1001001/HamsterKombatBot#4]
SyntaxError: f-string: unmatched '('

Problem in `" "`  in Client.py code syntex it should be `' '`

                    f"{self.limitCoinPrice:,}".replace(",",` " "`))
        logger.info(f"{'Level:'.ljust(30, `" "`)}\t" + 
                    f"{CLIENT_LEVEL.get(self.level, "")}")
        logger.info("Total keys".ljust(30, `" "`) + "\t" + 

Corrected code will be 
```
                 f"{self.limitCoinPrice:,}".replace(",", `' '`))
        logger.info(f"{'Level:'.ljust(30, `' '`)}\t" + 
                    f"{CLIENT_LEVEL.get(self.level, ' ')}")
        logger.info("Total keys".ljust(30,` ' '`) + "\t" + 
```

**Comment by fastnfuriousbd** [comment]
SyntaxError: f-string: unmatched '('

**Comment by Q1001001** [comment]
Thanks. Already fixed
only this line

```
logger.info(f"{'Level:'.ljust(30, `" "`)}\t" + 
                f"{CLIENT_LEVEL.get(self.level, "")}")
```
